### ISSUE TITLE
Illuminate\Events\Dispatcher::fire() error, removed in Laravel 5.8?

### ISSUE THREAD

**Issue by wiretail** [laravel-notification-channels/pushover#47]
In src/PushoverChannel.php the $this->events->fire() call seems to have been deprecated and removed in Laravel 5.8.

Not sure if it was added later again at some point, as this package I think was working in a Laravel 7.x app, but it is currently failing with `laravel Method Illuminate\Events\Dispatcher::fire does not exist.` in 7.25.0 at least.

Not sure if there is any reason not to change this to dispatch(), since older 5.x appears to longer be supported.  The change done manually works for me at the moment.

Removal Reference: https://github.com/laravel/framework/pull/26392

Thanks!

**Comment by Kovah** [comment]
Issue can be closed, it was fixed with commit https://github.com/orumad/laravel-pushover/commit/b3358420286d51d26c57b69787368100925c13b7

**Comment by tomslominski** [comment]
Was this ever actually fixed? The issue still seems to be present in the source? https://github.com/laravel-notification-channels/pushover/blob/master/src/PushoverChannel.php#L58

**Comment by nerdalertdk** [comment]
Just got this error also, Pushover API did not answer then this error came
I'm using Laravel 8, channels/pushover 3.0.0 still on php7.4 so can't upgrade to 3.1

```
GuzzleHttp\Exception\ConnectException: Connection refused for URI [https://api.pushover.net/1/](https://api.pushover.net/1/groups/)
```


```
BadMethodCallException: Method Illuminate\Events\Dispatcher::fire does not exist. in /data/www/vhosts/notus.asom-net.dk/vendor/laravel/framework/src/Illuminate/Macroable/Traits/Macroable.php:113
--
Stack trace:
#0 /data/www/vhosts/notus.asom-net.dk/vendor/laravel-notification-channels/pushover/src/PushoverChannel.php(59): Illuminate\Events\Dispatcher->__call()

#1 /data/www/vhosts/notus.asom-net.dk/vendor/laravel-notification-channels/pushover/src/PushoverChannel.php(52): NotificationChannels\Pushover\PushoverChannel->fireFailedEvent()


```
